{
  "formatVersion": "1.1",
  "component": {
    "group": "com.librity.checkpermission",
    "module": "checkpermission",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "2d2r4rrtvnh2lbompyrassqdti"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "checkpermission-1.0.jar",
          "url": "checkpermission-1.0.jar",
          "size": 17991,
          "sha512": "22533765ec987b16a6c93f2aeb171210211ef9963d43acf4d23e70c2f04b9e0cfa64497cee3e943c7c6e73174797ecad6ccc77e8852f8fa8116d4d204a25537f",
          "sha256": "e534dff8e69a4839ab545b0d4dce4c4047a84f4865927d144c69dca848fdb01b",
          "sha1": "5f37bbe4154deb42581bc4d02f351936762d6f1c",
          "md5": "91fd212580133a1fd7b5d17072c94307"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checkpermission-1.0.jar",
          "url": "checkpermission-1.0.jar",
          "size": 17991,
          "sha512": "22533765ec987b16a6c93f2aeb171210211ef9963d43acf4d23e70c2f04b9e0cfa64497cee3e943c7c6e73174797ecad6ccc77e8852f8fa8116d4d204a25537f",
          "sha256": "e534dff8e69a4839ab545b0d4dce4c4047a84f4865927d144c69dca848fdb01b",
          "sha1": "5f37bbe4154deb42581bc4d02f351936762d6f1c",
          "md5": "91fd212580133a1fd7b5d17072c94307"
        }
      ]
    }
  ]
}
